# Matrix Operations

In [4]:
import numpy as np
import pandas as pd

## a. Create a matrix as follows.

In [7]:
x = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

## b. Create a vector as follows

In [10]:
y = np.array([1,2,3,4,5,6])
y

array([1, 2, 3, 4, 5, 6])

## c. Select and display 𝑋13 , 𝑋22 , 𝑋32

In [17]:
print(x[0][2])
print(x[1][1])
x[2][1]

3
6


10

## d. Select and display the first three and the last three elements of 𝑦 separately

In [21]:
print(f"first 3 elements: {y[0:3]}")
print(f"last 3 elements: {y[-1:-4:-1]}")

first 3 elements: [1 2 3]
last 3 elements: [6 5 4]


## e. Find the size, number of elements and number of dimensions of both 𝑋 and 𝑦.

In [33]:
print(f"number of elements of x: {x.size}")
print(f"number of elements of y: {y.size}")
print(f"shape of x: {x.shape}")
print(f"shape of y: {y.shape}")
print(f"dimension of x: {len(x.shape)} D")
print(f"dimension of y: {len(y.shape)} D")

number of elements of x: 12
number of elements of y: 6
shape of x: (3, 4)
shape of y: (6,)
dimension of x: 2 D
dimension of y: 1 D


## f. Generate and display 𝑋10 = 𝑋 + 10.

In [20]:
x[1][0] = x[1][0] + 10 
x[1][0]

15

## g. Find the maximum and minimum values of both 𝑋 and 𝑦.

In [35]:
print(f"max of x: {x.max()}")
print(f"min of x: {x.min()}")
print(f"max of y: {y.max()}")
print(f"min of y: {y.min()}")

max of x: 12
min of x: 1
max of y: 6
min of y: 1


## h. Calculate the and display Average, Variance, and Standard Deviation

In [57]:
x_avg = np.average(x)
print(f"avg: {x_avg}")
x_var = np.var(x)
print(f"var: {x_var}")
x_std = np.std(x)
print(f"std: {x_std}")

avg: 6.5
var: 11.916666666666666
std: 3.452052529534663


## i. Reshape 𝑋 as a 2 × 6 matrix

In [30]:
np.reshape(x,(2,6))

array([[ 1,  2,  3,  4, 15,  6],
       [ 7,  8,  9, 10, 11, 12]])

## j. Find and display the transpose of both 𝑋 and 𝑦.

In [32]:
np.transpose(x)

array([[ 1, 15,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [33]:
np.transpose(y)

array([1, 2, 3, 4, 5, 6])

## k. Flatten 𝑋 and display.

In [35]:
x.flatten()

array([ 1,  2,  3,  4, 15,  6,  7,  8,  9, 10, 11, 12])

## l. Generate a 3 × 3 square matrix (𝑃).

In [59]:
p = np.array([[1,3,6],[1,4,5],[2,2,7]])

## m. Find and display the rank.

In [41]:
len(p.shape)

2

## n. Find and display the determinant of 𝑃.

In [43]:
np.linalg.det(p)

-8.999999999999998

## o. Find and display the diagonal of 𝑃.

In [45]:
p.diagonal()

array([1, 4, 7])

## p. Find and display the trace of 𝑃.

In [47]:
p.trace()

12

## q. Find the eigen values and eigen vectors of p.

In [49]:
np.linalg.eigvals(p)

array([10.59900683, -0.45701438,  1.85800755])

In [50]:
val, vec = np.linalg.eig(p)

In [51]:
vec

array([[-0.55902488, -0.95323847, -0.18562955],
       [-0.55289125, -0.10432388, -0.88924337],
       [-0.61790165,  0.2836423 ,  0.41807643]])

## r. Generate 𝑧 = [2, 3, 6, 2, 5 2]. Find the dot product between 𝑦 and 𝑧.

In [61]:
z = np.array([2,3,6,2,5,2])
np.dot(y,z)

71

## s. Generate a 3 × 3 square matrix (𝑄).

In [63]:
q = np.array([[4,6,7],[5,5,2],[3,4,6]])

In [57]:
print(p+q)

[[ 5  9 13]
 [ 6  9  7]
 [ 5  6 13]]


In [58]:
print(p-q)

[[-3 -3 -1]
 [-4 -1  3]
 [-1 -2  1]]


## t. Find and display element wise product of P and Q.

In [99]:
p*q

array([[ 4, 18, 42],
       [ 5, 20, 10],
       [ 6,  8, 42]])

## u. Find and display inverse of of P and Q.

In [103]:
np.linalg.inv(p)

array([[-2.        ,  1.        ,  1.        ],
       [-0.33333333,  0.55555556, -0.11111111],
       [ 0.66666667, -0.44444444, -0.11111111]])

In [109]:
np.linalg.inv(q)

array([[-1.04761905,  0.38095238,  1.0952381 ],
       [ 1.14285714, -0.14285714, -1.28571429],
       [-0.23809524, -0.0952381 ,  0.47619048]])

## v. Generate 10 no.s of random numbers of uniform, gaussian and logistic distributions.

In [120]:
np.random.seed(42)
uniform_num = np.random.uniform(0,1,10)
gaussian_num = np.random.normal(0,1,10)
logistic_num = np.random.logistic(0,1,10)

In [124]:
print(uniform_num)
print(gaussian_num)
print(logistic_num)

[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864 0.15599452
 0.05808361 0.86617615 0.60111501 0.70807258]
[-0.46947439  0.54256004 -0.46341769 -0.46572975  0.24196227 -1.91328024
 -1.72491783 -0.56228753 -1.01283112  0.31424733]
[-0.88499072 -0.54785657 -0.17617432  1.29608858 -1.38833447  0.05695314
  0.37395612 -3.02180608  0.43700374 -1.58191725]
